[droid-hal] Ignore any previously existing files
mer-hybris/droid-hal-sony-ganges-pie pull request #25
Opened 2019-10-08 23:36 UTC by Thaodan

2019-10-09 09:58 UTC, Thaodan commented
No ln would create the symlink into 
the existing folder if the target file is a 
folder eg. previously copied folders.

2020-10-03 13:34 UTC, sledges requested changes

2020-10-03 13:34 UTC, sledges commented on setup-sources.sh
> +ln -sf ../../../../../../../fw-api kernel/sony/msm-4.9/kernel/drivers/staging/wlan-qc/fw-api
If the folder above is removed, when symlinking we don't really need the --force option anymore.

2020-10-05 11:16 UTC, sledges approved these changes

2020-10-05 11:19 UTC, sledges requested changes
Please check the commit history of this repo and reword your commit message accordingly (I also suggest to talk about submodules, instead of files, for clarity):
```
kernel: Ignore any previously existing content of submodules

[kernel] Ignore any previously existing content of submodules
```

2020-10-05 12:25 UTC, sledges approved these changes

2020-10-05 12:26 UTC, merged